apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f67b9i89o-python
  janus-idp.io/tekton: f67b9i89o-python
  backstage.io/kubernetes-id: f67b9i89o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f67b9i89o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
