apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f67b9i89o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f67b9i89o-python 
  name: f67b9i89o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f67b9i89o-python 
